# Generated by Django 4.2.7 on 2025-05-31 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(default='fa-utensils', max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('fake_payment_id', models.CharField(blank=True, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='dishes/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)')),
                ('composition', models.TextField(blank=True, verbose_name='Состав')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калории')),
                ('proteins', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Белки')),
                ('fats', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Жиры')),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Углеводы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
