# Generated by Django 4.2.7 on 2025-05-19 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(default='fa-utensils', max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото')),
                ('weight', models.PositiveIntegerField(default=300, verbose_name='Вес (г)')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Калории')),
                ('protein', models.FloatField(default=0.0, verbose_name='Белки')),
                ('fat', models.FloatField(default=0.0, verbose_name='Жиры')),
                ('carbs', models.FloatField(default=0.0, verbose_name='Углеводы')),
                ('spicy', models.IntegerField(choices=[(0, 'Не острое'), (1, 'Легкая острота'), (2, 'Острое'), (3, 'Очень острое')], default=0, verbose_name='Острота')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['category', 'name'],
            },
        ),
    ]
