# Generated by Django 4.2.7 on 2025-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото блюда', null=True, upload_to='dishes/', verbose_name='Изображение'),
        ),
    ]
